fix various display issues with fill in the blank questions
empirical-org/Empirical-Core pull request #11697
Opened 2024-03-28 13:13 UTC by emilia-friedberg

## WHAT
Fix various display issues with fill in the blank questions, including lack of respect for line breaks, weirdly broken lines, overlapping input fields, and unnecessarily large .

## WHY
As we add more complicated fill in the blank questions to both the Diagnostic and Connect, these changes are necessary so that they display properly.

## HOW
Mostly CSS, though I also updated the React to a) parse the HTML so that we add linebreaks (`<br />`s) where the WYSIWYG editor was outputting `<p>` tags (we can't keep them as `<p>` tags because we have to split up the generated text into `<span>`s and `<input>`s for the activity) and b) adjust the width of the input field so that it starts at the width of the shortest cue (or at least three characters) and expands to fit whatever the user has written.

### Screenshots
<img width="576" alt="Screenshot 2024-03-28 at 9 03 44 AM" src="https://github.com/empirical-org/Empirical-Core/assets/18669014/4011c13f-da70-47c8-ac5d-839be59bb981">
<img width="580" alt="Screenshot 2024-03-28 at 9 02 36 AM" src="https://github.com/empirical-org/Empirical-Core/assets/18669014/6dc8b801-1e04-4b35-bb9c-858f4e9bea30">
<img width="581" alt="Screenshot 2024-03-28 at 9 01 56 AM" src="https://github.com/empirical-org/Empirical-Core/assets/18669014/1706344b-f2c4-46d7-96b5-569ac2dbd1f9">
<img width="587" alt="Screenshot 2024-03-28 at 9 01 16 AM" src="https://github.com/empirical-org/Empirical-Core/assets/18669014/2e3a6fa0-be60-4251-8f22-44d15eb4badc">
<img width="585" alt="Screenshot 2024-03-28 at 9 00 45 AM" src="https://github.com/empirical-org/Empirical-Core/assets/18669014/3ca11f8c-29d9-4604-b02e-d82fcad9acc3">

### Notion Card Links
https://www.notion.so/quill/Improve-Fill-in-the-blank-question-formatting-in-Diagnostic-Connect-to-make-questions-easier-for-s-9928294a292a48fb8931d8ec06caaf4f?pvs=4

### What have you done to QA this feature?
Tested a bunch of the problematic questions on staging and confirmed that they look good now, and asked Jamie and Rachel to QA as well.

PR Checklist | Your Answer
------------ | -------------
Have you added and/or updated tests? | YES
Have you deployed to Staging? | YES
Self-Review: Have you done an initial self-review of the code below on Github? | YES

2024-03-28 17:37 UTC, happythenewsad requested changes
Looks great besides the function refactor

2024-03-28 17:37 UTC, happythenewsad commented on services/QuillLMS/client/app/bundles/Connect/components/studentLessons/fillInBlank.tsx
> +    const splitPrompt = question.prompt.replace(/<\/p><p>/g, '</br>').replace(/^<p>/g, '').replace(/<p>/g, '<br/>').replace(/<\/p>/g, '').split('___');
This function is implemented three times. Let's refactor it into a shared function. As a bonus, we'll also get to name it, which will add a bit of self documentation.

2024-03-29 16:09 UTC, happythenewsad approved these changes

2024-04-01 09:19 UTC, cissyxyu approved these changes

2024-04-01 12:41 UTC, merged