Change "My" to "Manage" in all copy for teacher tabs
empirical-org/Empirical-Core pull request #12210
Opened 2024-08-06 13:53 UTC by cissyxyu

## WHAT
Rename the teacher tabs "My []" to "Manage []" and "My Reports" to "View Reports".

## WHY
This is more in line with standard naming in ed-tech apps.

## HOW
Just copy changes -- change the string constants to reflect the new naming.

### Screenshots
<img width="743" alt="Screenshot 2024-08-06 at 9 48 28 PM" src="https://github.com/user-attachments/assets/39821ec4-9860-41cc-ae39-0789c0e3a57d">

### Notion Card Links
https://www.notion.so/quill/1-Update-Names-for-Primary-Navigation-Tabs-7484e4a03ba84253b50e85cdd1bd2a03?pvs=4

### What have you done to QA this feature?
Deploy to staging and verify that teachers see the new copy on all front end.

PR Checklist | Your Answer
------------ | -------------
Have you added and/or updated tests? |  yes
Have you deployed to Staging? | yes
Self-Review: Have you done an initial self-review of the code below on Github? | yes

2024-08-06 14:41 UTC, eadams17 requested changes
This looks good-- just some clean up I think we should do within the `navigation_helper` file to match the new naming convention

2024-08-06 14:41 UTC, eadams17 commented on services/QuillLMS/app/helpers/navigation_helper.rb
> +  MY_REPORTS = 'View Reports'
we should change these const names to match the strings

also, in this same file, we should update the definition names (i.e. `my_classes_tab`, etc)

2024-08-06 15:25 UTC, eadams17 approved these changes

2024-08-07 15:17 UTC, anathomical approved these changes
I appreciate the updates to the variable names that you included as part of this.

2024-08-07 15:45 UTC, emilia-friedberg approved these changes
LGTM!

2024-08-08 02:21 UTC, merged