Add manifest.json file for PWA installs
empirical-org/Empirical-Core pull request #12328
Opened 2024-09-04 07:09 UTC by cissyxyu

## WHAT
In order for our website to be "installable" as a web "app" that can be then opened through the Mac/Windows application dock and phone home screens, we need to add a manifest.json files that designates some properties and icons.

## WHY
This way, a portion of users who like this functionality can "install" Quill to quickly open from their home screens without going through an extra web browser.

## HOW
Add a manifest.json files with required attributes, and serve it from a GET request to a static controller.

### Screenshots
<img width="282" alt="Screenshot 2024-09-04 at 2 45 35 PM" src="https://github.com/user-attachments/assets/cad948b4-05a9-49c0-ac61-a0ef350734a3">
<img width="190" alt="screenshot" src="https://github.com/user-attachments/assets/beda52b8-8b20-4f74-8794-9395a262a8a1">

### Notion Card Links
https://www.notion.so/quill/Product-Board-30f97e4eb01246dbb8264253fb385073?p=9c9a9512c6e44585907cbdde6c35f6db&pm=c

### What have you done to QA this feature?
I've tested it by downloading my own staging site as an app through Mac Desktop, using my iPhone to download it as an app, and asking Thomas to verify downloading on his Android phone.

PR Checklist | Your Answer
------------ | -------------
Have you added and/or updated tests? |  yes
Have you deployed to Staging? | yes
Self-Review: Have you done an initial self-review of the code below on Github? | yes

2024-09-04 16:43 UTC, anathomical requested changes
I believe that you may be able to simplify this by simply stashing your `manifest.json` file in the `public/` folder where `robots.txt` is stored.  I think this will allow you to skip the need to define a route since routing should fall through to looking for static files in `public/` if there's no defined route.

I could be wrong, but I'm pretty sure that should work.

2024-09-05 07:02 UTC, cissyxyu commented
> I believe that you may be able to simplify this by simply stashing your `manifest.json` file in the `public/` folder where `robots.txt` is stored. I think this will allow you to skip the need to define a route since routing should fall through to looking for static files in `public/` if there's no defined route.
> 
> I could be wrong, but I'm pretty sure that should work.

Yes, that worked! Thanks for the tip, it saves a lot of work.

2024-09-05 13:06 UTC, emilia-friedberg approved these changes
So cool to have this working!

2024-09-06 16:18 UTC, anathomical approved these changes

2024-09-10 02:42 UTC, merged