Add highlight groups
empirical-org/Empirical-Core pull request #12650
Opened 2024-12-11 16:40 UTC by brendanshean

## WHAT
Add `Evidence::HighlightGroup` model
Add `optimal_feedback` attribute to `Evidence::Prompt`
Add `highlight_group_id` to `Evidence::Highlight`
Add validation 
## WHY

## HOW

### Screenshots
(If applicable. Also, please censor any sensitive data)

### Notion Card Links
https://www.notion.so/quill/Production-Evidence-GenAI-Check-144d42e6f94180268bebc8989c25c7a1?pvs=4

### What have you done to QA this feature?
(Provide enough detail that a reviewer could assess whether additional QA should be done. For larger projects, additionally use the Engineer Feature Testing Notion template. Review Guidelines if needed: https://www.notion.so/quill/Github-PR-QA-Guidelines-49e99fc965654ceeb8c6249bd9d181d7)

PR Checklist | Your Answer
------------ | -------------
Have you added and/or updated tests? |  (The answer should mostly be 'YES'. If you answer 'NO', please justify.)
Have you deployed to Staging? | (Possible answers: YES, Not yet - deploying now!, NO - non-app change, NO - tiny change)
Self-Review: Have you done an initial self-review of the code below on Github? |

2024-12-11 17:49 UTC, dandrabik requested changes
Thanks for pushing this forward. So I left a comment with more details, but the general ask I have is to write tests for the methods in the Highlight class and make them work for both types of highlight associations. I suggested a few different paths that you could do, and will defer to you. Happy to discuss.

2024-12-11 17:49 UTC, dandrabik commented on services/QuillLMS/db/structure.sql
> +    feedback_id integer,
Hmm, so you are reusing the current `Evidence::Highlight` class for both, and some will have a `feedback_id` and some will have a `highlight_group_id`. If you go this route, you'd have to add conditional logic (`feedback` or `highlight_group`) to [most methods in the highlight class](https://github.com/empirical-org/Empirical-Core/blob/develop/services/QuillLMS/engines/evidence/app/models/evidence/highlight.rb#L20-L110). So as part of this code, we'd need to make the highlight class methods still work in both setups (it'll be easy to write some failing tests for these).

Some paths you might consider:
1) Write one (or two) conditional methods that are used by other methods to point to the relevant object (feedback or rule or whatever)
2) Making the relationship polymorphic
3) A separate class for GenAI Highlights and copy the relevant code

2024-12-12 17:38 UTC, brendanshean commented on services/QuillLMS/engines/evidence/app/models/evidence/gen_ai.rb
Note this is needed to get the annotations working properly.

2024-12-12 17:43 UTC, brendanshean commented on services/QuillLMS/engines/evidence/app/models/evidence/gen_ai.rb
This is needed to get annotations working properly.

2024-12-12 17:48 UTC, brendanshean commented on services/QuillLMS/engines/evidence/app/models/evidence/gen_ai.rb
This is needed to get annotations working for Evidence::GenAI::{Highlight, HighlightGroup}

2024-12-12 17:52 UTC, brendanshean commented on services/QuillLMS/engines/evidence/app/models/evidence/gen_ai.rb
schema annotations for `Evidence::GenAI::{Highlight, HighlightGroup}` need this file to work properly.

2024-12-12 17:55 UTC, brendanshean commented on services/QuillLMS/engines/evidence/app/models/evidence/gen_ai.rb
schema annotations for Evidence::GenAI::{Highlight, HighlightGroup} need this file to work properly.

2024-12-12 19:02 UTC, dandrabik approved these changes
So, I think you can drop two of the DB columns for now, but otherwise this looks good! Thanks for moving this along!

2024-12-12 19:02 UTC, dandrabik commented on services/QuillLMS/db/migrate/20241211155124_create_evidence_gen_ai_highlights.evidence.rb
> +      t.integer :starting_index
For these two columns, I wasn't sure about this, but I just confirmed that 100% of the data in the existing highlights table has highlight_type: 'passage' and starting_index: 0. We could probably drop these two columns for now and hard-code those values (and adjust later if necessary).

Just as an FYI, the other highlight_types: 'grammar' and 'spelling' are generated dynamically, i.e. which word to highlight, so they aren't in the DB. They are also the only ones to use `starting_index` and they use it because you could misspell the same word twice in your entry, but there was a feature request to only highlight the first misspelling (so as to not give the student multiple things to fix).

![Screenshot 2024-12-12 at 1 55 45 PM](https://github.com/user-attachments/assets/cd15383f-c7e6-4d0c-ac9a-63a8e4fe1ed7)

2024-12-12 19:02 UTC, dandrabik commented on services/QuillLMS/engines/evidence/spec/models/evidence/gen_ai/highlight_spec.rb
> +      describe '#valid_in_all_targets' do
Nice tests here!

2024-12-12 21:55 UTC, merged