comprehension/tweak-go-used-calculation
empirical-org/Empirical-Core pull request #7492
Opened 2021-04-20 18:24 UTC by anathomical

## WHAT
Use a deterministically determined loop order
## WHY
The return logic assumes that the loop will look over items in priority order (and thus early exit on the highest priority item that matches the return criteria), but the loop in place at the moment does NOT actually do this because `range feedbacks` provides a non-deterministic iteration order.
## HOW
Because items are placed into the map keyed on their priority, it turns out to be the case that the range of `int`s equal to the `len` of the map will give us every item in order of priority.

### Notion Card Links
https://www.notion.so/quill/Bug-Report-User-Feedback-does-not-Match-Report-Feedback-fc313a2a44ff4cb0a1adf20015077cca

PR Checklist | Your Answer
------------ | -------------
Have you added and/or updated tests? |  No behavior changes that can be tested reproducibly
Have you deployed to Staging? | Yes
Self-Review: Have you done an initial self-review of the code below on Github? | Yes
Design Review: If applicable, have you compared the coded design to the mockups? | N/A

2021-04-20 19:35 UTC, dandrabik requested changes
Thanks for finding this bug. Let's add tests for this. This is a pure function, so should be easily testable (a test on this function should have caught the original bug).

2021-04-20 19:37 UTC, happythenewsad requested changes
map order cannot be relied upon in golang, according to the spec: https://golang.org/ref/spec#RangeClause

2021-04-20 19:39 UTC, happythenewsad commented
> map order cannot be relied upon in golang, according to the spec: https://golang.org/ref/spec#RangeClause

Disregard, you're not relying on order

2021-04-20 20:27 UTC, anathomical commented
@dandrabik There actually was a test case for this function already, but it didn't capture the edge case that could give rise to this intermittent failure.  I've updated the case with data that should cover this failure state and run it a couple of times successfully, so hopefully it would catch intermittent errors of this class if they come up in the future.

2021-04-21 13:18 UTC, dandrabik approved these changes
:+1: LGTM. Thanks for adding/improving the test!

2021-04-21 17:22 UTC, happythenewsad approved these changes

2021-04-21 20:00 UTC, merged