wip
empirical-org/Empirical-Core pull request #7549
Opened 2021-04-29 15:34 UTC by happythenewsad

## WHAT

## WHY

## HOW

### Screenshots
(If applicable. Also, please censor any sensitive data)

### Notion Card Links
(Please provide links to any relevant Notion card(s) relevant to this PR.)

PR Checklist | Your Answer
------------ | -------------
Have you added and/or updated tests? |  (The answer should mostly be 'YES'. If you answer 'NO', please justify.)
Have you deployed to Staging? | (Possible answers: YES, Not yet - deploying now!, NO - non-app change, NO - tiny change)
Self-Review: Have you done an initial self-review of the code below on Github? |
Design Review: If applicable, have you compared the coded design to the mockups? | (N/A or Yes)

2021-04-29 17:55 UTC, happythenewsad commented on services/comprehension/feedback-api-main/src/endpoint/endpoint.go
> +func AssembleUrls() ([8]string) {
this is kinda gross

2021-05-04 17:06 UTC, anathomical requested changes
Looks like a pretty clean set of changes.  Might be worth adding some unit tests for the URL generating functions just to clearly communicate expectations?  Could probably be convinced that we shouldn't wait on those, but I imagine they're pretty simple tests.

2021-05-04 17:06 UTC, anathomical commented on services/comprehension/feedback-api-main/src/endpoint/endpoint.go
> +var automl_index = 3
Can we not keep this as a `const`?

2021-05-04 18:36 UTC, happythenewsad commented on services/comprehension/feedback-api-main/src/endpoint/endpoint.go
> +var automl_index = 3
yes

2021-05-06 14:56 UTC, anathomical approved these changes

2021-05-06 15:02 UTC, merged