Lms/comprehension prompt health report performance
empirical-org/Empirical-Core pull request #7790
Opened 2021-06-11 21:31 UTC by anathomical

## WHAT
Refactor the Prompt Health query to be pure SQL rather than doing Ruby-based post-processing on a simpler query
## WHY
The loops in the post-processing were causing performance issues, so we're moving all the logic in to SQL in order to improve performance
## HOW
Write a relatively complex aggregate SQL query to do all of the calculations that we care about in SQL

### Notion Card Links
https://www.notion.so/quill/Comprehension-Prompt-Health-Endpoint-Performance-cefc25b427494bc18a87084909acc794

PR Checklist | Your Answer
------------ | -------------
Have you added and/or updated tests? |  Yes
Have you deployed to Staging? | Not yet - deploying now!
Self-Review: Have you done an initial self-review of the code below on Github? | Yes
Design Review: If applicable, have you compared the coded design to the mockups? | N/A

2021-06-14 19:27 UTC, happythenewsad requested changes
This looks promising - nice work. Just a trivial change request. Also, it would be a good idea to run EXPLAIN ANALYZE on this PR and compare with `develop`.

2021-06-14 19:27 UTC, happythenewsad commented on services/QuillLMS/app/queries/prompt_feedback_history.rb
> +        #promptwise_postprocessing promptwise_sessions(activity_id)
Missed a line here

2021-06-15 18:15 UTC, anathomical commented on services/QuillLMS/app/queries/prompt_feedback_history.rb
> +        #promptwise_postprocessing promptwise_sessions(activity_id)
Good catch.  Fixed.

2021-06-15 18:17 UTC, anathomical commented
@happythenewsad We could run `EXPLAIN ANALYZE`, but in this case I'm not sure what it would demonstrate.  NewRelic tracing suggests that the time-spent in the current endpoint is mostly in Ruby, not in SQL, so we wouldn't actually expect this query to be more performant than the one we've been using on its face.  We just expect the whole call to be more performant.

2021-06-15 19:29 UTC, happythenewsad commented
> We just expect the whole call to be more performant.

Yes, we expect the whole call to be more performant. I inquired because I want to avoid the SQL call getting too expensive. That said, I'm fine with trying it out in prod.

2021-06-15 19:29 UTC, happythenewsad approved these changes

2021-06-22 14:16 UTC, merged