Teacher dashboard/ rearrange classes
empirical-org/Empirical-Core pull request #7869
Opened 2021-07-01 22:06 UTC by eadams17

## WHAT
add the ability to rearrange teacher classes on the dashboard

## WHY
teachers have requested this feature to be able to better organize their classes

## HOW
move the teacher cards into a sortable list and store the classroom sorted order in `localStorage`

### Screenshots
(If applicable. Also, please censor any sensitive data)
<img width="954" alt="Screen Shot 2021-07-01 at 4 57 38 PM" src="https://user-images.githubusercontent.com/25959584/124194592-79e20980-da8e-11eb-8c5b-0ecaaf125851.png">

### Notion Card Links
(Please provide links to any relevant Notion card(s) relevant to this PR.)
https://www.notion.so/quill/Allow-teachers-to-re-arrange-classes-642d0f6b976d486db6df1aaa34d89ee6

PR Checklist | Your Answer
------------ | -------------
Have you added and/or updated tests? |  Yes
Have you deployed to Staging? | Yes
Self-Review: Have you done an initial self-review of the code below on Github? | Yes
Design Review: If applicable, have you compared the coded design to the mockups? | Yes

2021-07-02 17:01 UTC, anathomical approved these changes
This looks fine, but are we okay with this order only being in localStorage?  Did we talk to Peter S about that just so he knows that's how we're implementing it?  (Probably fine, just don't want anyone to be surprised.)

2021-07-20 13:39 UTC, emilia-friedberg approved these changes

2021-07-21 16:07 UTC, anathomical requested changes
Looks good.  I would like to see a couple more test cases around sorting, but all of the code looks good to me.

2021-07-21 16:07 UTC, anathomical commented on services/QuillLMS/spec/controllers/classrooms_teachers_controller_spec.rb
> +  describe '#update_order' do
Nice.  Love the tests.

2021-07-21 16:07 UTC, anathomical commented on services/QuillLMS/app/controllers/teachers/classrooms_controller.rb
> +    classrooms = has_classroom_order ? classrooms.includes(:classrooms_teachers).order('classrooms_teachers.order') : classrooms.order(created_at: :desc)
Might be worth adding a test case for this behavior, just to ensure that we don't break sorting later on somehow.  So a case where they all have order, and a case where only some have order, would probably cover us here.

2021-07-21 23:13 UTC, anathomical approved these changes

2021-07-22 12:37 UTC, merged