rename files on the frontend from Comprehension to Evidence
empirical-org/Empirical-Core pull request #8151
Opened 2021-08-25 17:31 UTC by emilia-friedberg

## WHAT
Rename frontend file structures to use "Evidence" instead of "Comprehension" and update all references to them.

## WHY
This is part of a larger effort to change the name so we are consistent.

## HOW
Lots of global searching, replacing, and manual testing. I know there are a bajillion files here!

### Screenshots
(If applicable. Also, please censor any sensitive data)

### Notion Card Links
https://www.notion.so/quill/Rename-Comprehension-bundle-Evidence-d9ecc24b7b6f4553a88abdea5bc43d8a

PR Checklist | Your Answer
------------ | -------------
Have you added and/or updated tests? | YES
Have you deployed to Staging? | YES
Self-Review: Have you done an initial self-review of the code below on Github? | YES
Spec Review: Have you reviewed the spec and ensured this meets requirements and/or matches design mockups? | YES

2021-08-25 21:27 UTC, eadams17 approved these changes
🥵

2021-08-27 15:20 UTC, anathomical requested changes
Nice job on a pretty labor-intensive and repetitive task.  One question about using a hard-coded variable instead of one pulled from ENV that I think needs addressing, but all the other changes seem solid to me.

2021-08-27 15:20 UTC, anathomical commented on services/QuillLMS/client/app/bundles/Evidence/actions/session.ts
> +    const feedbackURL = `https://comprehension-feedback.quill.org/`
Should we keep pulling this from `ENV`?  This config change will make every environment go to the production endpoint rather than using Staging in Staging and so on.

2021-08-27 16:26 UTC, emilia-friedberg commented on services/QuillLMS/client/app/bundles/Evidence/actions/session.ts
> +    const feedbackURL = `https://comprehension-feedback.quill.org/`
Yes, thank you! This made its way in accidentally.

2021-09-01 19:59 UTC, anathomical approved these changes

2021-09-02 13:32 UTC, merged