Evidence/ fix sessions total
empirical-org/Empirical-Core pull request #8178
Opened 2021-08-31 23:32 UTC by eadams17

## WHAT
fix the sessions total in the internal tool

## WHY
we want the sessions total to show the accurate amount of sessions

## HOW
add a `get_total_count` method to `FeedbackHistory` to pass back to the frontend for 'total_activity_sessions' 

### Screenshots
(If applicable. Also, please censor any sensitive data)

### Notion Card Links
(Please provide links to any relevant Notion card(s) relevant to this PR.)
https://www.notion.so/quill/Make-sure-the-View-Sessions-Total-1b2f4a0335ac4d83bc5b67d2628da59d

PR Checklist | Your Answer
------------ | -------------
Have you added and/or updated tests? |  Yes
Have you deployed to Staging? | Yes
Self-Review: Have you done an initial self-review of the code below on Github? | Yes
Spec Review: Have you reviewed the spec and ensured this meets requirements and/or matches design mockups? | Yes

2021-09-01 14:53 UTC, happythenewsad requested changes

2021-09-01 14:53 UTC, happythenewsad commented on services/QuillLMS/app/models/feedback_history.rb
> +  def self.get_total_count(activity_id: nil, page: 1, start_date: nil, end_date: nil, page_size: DEFAULT_PAGE_SIZE, turk_session_id: nil, filter_type: nil)
Since `page_size` and `filter_type` are not used in the implementation, we should remove them from the method signature.

2021-09-01 14:53 UTC, happythenewsad commented on services/QuillLMS/spec/models/feedback_history_spec.rb
> +    context '#get_total_count' do
How about covering the turk_session_id code branch as well?

2021-09-01 14:53 UTC, happythenewsad commented on services/QuillLMS/app/models/feedback_history.rb
> +    query = FeedbackHistory.select(:feedback_session_uid).distinct
This `distinct` is redundant, given the `group` operation below

2021-09-02 13:42 UTC, emilia-friedberg approved these changes

2021-09-02 20:16 UTC, happythenewsad approved these changes
LGTM

2021-09-09 15:58 UTC, merged