universal rules update rake task
empirical-org/Empirical-Core pull request #8314
Opened 2021-09-24 20:13 UTC by happythenewsad

## WHAT

## WHY

## HOW

### Screenshots
(If applicable. Also, please censor any sensitive data)

### Notion Card Links
(Please provide links to any relevant Notion card(s) relevant to this PR.)

PR Checklist | Your Answer
------------ | -------------
Have you added and/or updated tests? |  (The answer should mostly be 'YES'. If you answer 'NO', please justify.)
Have you deployed to Staging? | (Possible answers: YES, Not yet - deploying now!, NO - non-app change, NO - tiny change)
Self-Review: Have you done an initial self-review of the code below on Github? |
Spec Review: Have you reviewed the spec and ensured this meets requirements and/or matches design mockups? | (N/A or Yes)

2021-10-06 18:44 UTC, happythenewsad commented
@anathomical @emilia-friedberg

2021-10-07 18:54 UTC, anathomical requested changes
Need to figure out what behavior we actually want if there's a rule with the specified UID but it's somehow not universal or has the wrong type.

2021-10-07 18:54 UTC, anathomical commented on services/QuillLMS/app/lib/universal_rule_loader.rb
> +        )
If this fires because of the second two conditions (not universal or not the right type) you'll attempt to create a new rule with the same UID which will fail due to uniqueness validation.

2021-10-07 18:54 UTC, anathomical commented on services/QuillLMS/spec/lib/universal_rule_loader_spec.rb
> +      it 'should create a new rule and new feedback' do
Need to figure out what behavior we want when there's an existing rule with the UID, but it's not universal or is the wrong type and add some test cases for that edge case behavior (which might just be to throw an error or something).

2021-10-08 14:12 UTC, emilia-friedberg approved these changes
LGTM other than Thomas's points, don't need to review again when those are made.

2021-10-11 20:40 UTC, anathomical approved these changes

2021-10-12 20:06 UTC, merged