opinion LMS endpoint
empirical-org/Empirical-Core pull request #8365
Opened 2021-10-07 03:47 UTC by happythenewsad

## WHAT
Move business logic from Opinion API into a new LMS endpoint, which calls Opinion API.

## WHY
So that OAPI and LMS are maximally decoupled, and so that we don't need to push complex config changes to oapi.

## HOW
New LMS endpoint. Also, a modification to OAPI's payload to support this.

### Screenshots
(If applicable. Also, please censor any sensitive data)

### Notion Card Links
https://www.notion.so/quill/Refactor-Evidence-Opinion-API-Flow-to-go-through-the-engine-93614b68aade43cc995e3277a491d4d3

PR Checklist | Your Answer
------------ | -------------
Have you added and/or updated tests? |  yes
Have you deployed to Staging? | not yet
Self-Review: Have you done an initial self-review of the code below on Github? | yes
Spec Review: Have you reviewed the spec and ensured this meets requirements and/or matches design mockups? | yes

2021-10-07 03:51 UTC, happythenewsad commented on services/QuillLMS/engines/evidence/evidence.gemspec
> +  s.add_dependency 'rails', '5.1.7'
No logic changes, just single quoting

2021-10-08 11:50 UTC, brendanshean approved these changes
Looks good.  Nice comment on the rspec stub_const item.

2021-10-11 22:18 UTC, dandrabik requested changes
Thanks for putting this together and good start on this. I'm requesting changes, since I believe the logic needs to be changed to properly handle API errors. I've also requested some structural changes to keep this code maintainable. 

Happy to jump on a call to walk through anything.

2021-10-11 22:18 UTC, dandrabik commented on services/QuillLMS/engines/evidence/lib/evidence/evidence/opinion_feedback_assembler.rb
> +      @top_feedback = feedbacks.empty? ? nil : feedbacks.min_by { |e| e.order }
These two lines could be:
```suggestion
      @top_feedback = @rule&.feedbacks.min_by(&:order)  
```

2021-10-11 22:18 UTC, dandrabik commented on services/QuillLMS/engines/evidence/lib/evidence/evidence/opinion_feedback_assembler.rb
> +      'Using Must' => '5545d756-9ba5-44d5-829a-0479cbbe941e',
I'm a little wary of using phrases with spaces, some capitalization, and some dashes as codes shared between two systems. In my experience, it's makes it easier to miss typos in coding and code review, e.g. if you listed `'Starts With Verb Check'` as a key in the opinion API, I'm not sure I'd notice the difference in review. Can we use snake case here, e.g. `using_must`?

Also, naming-wise, it would be nice to make these more consistent. Some have "Check", some don't. There are different verb forms, e.g. "Using Must", "Starts with Verb Check", and some don't have verbs (but could). 

These keys should have a clear pattern so if a check needs to be added, the format would be obvious, e.g. `must_check`, `first_person_reference_check`, etc.

2021-10-11 22:18 UTC, dandrabik commented on services/QuillLMS/engines/evidence/app/controllers/evidence/opinion_controller.rb
> +      oapi_response = Timeout.timeout(API_TIMEOUT) do
I think it would be better to move this code into an API wrapper that abstracts these request details and has methods for the two pieces of info that will be used, `rule_uid` and `highlight`, e.g. 
```ruby
request = OpinionAPIRequest.new(params['entry'], params['prompt_text'])
request.rule_uid
request.highlight

```
I think this will make the code more testable and maintainable.

2021-10-11 22:18 UTC, dandrabik commented on services/QuillLMS/engines/evidence/app/controllers/evidence/opinion_controller.rb
> +      assembler = OpinionFeedbackAssembler.new(oapi_response)
Following the comment above. We only need two pieces of information for this method, `rule_uid` and `highlight`. I think it would make the code clearer and more testable if those two were passed in, rather than the entire `HTTParty` response, since most of it isn't used.

2021-10-11 22:18 UTC, dandrabik commented on services/QuillLMS/engines/evidence/lib/evidence/evidence/opinion_feedback_assembler.rb
> +        'optimal': @rule&.optimal,
So if a rule is not found (an API error or a bug), I think this payload would return `optimal: nil`, when I believe we want this to be `optimal: true` so that the student doesn't receive this feedback.

2021-10-11 22:18 UTC, dandrabik commented on services/QuillLMS/engines/evidence/spec/controllers/evidence/opinion_controller_spec.rb
> +      context 'Rule.feedback exists' do
Let's add some tests for:
1. Opinion API raises a 500.
2. A key that isn't in the `OAPI_ERROR_TO_RULE_UID`.

I believe the payloads using the current code aren't what we'd want them to be.

2021-10-11 22:18 UTC, dandrabik commented on services/QuillLMS/engines/evidence/spec/controllers/evidence/opinion_controller_spec.rb
> +          'concept_uid' => 'ConceptUID',
If we are checking the expectation of `concept_uid` and `optimal`, we should explicitly set those when creating the evidence rule, or confirm they match the `rule.concept_uid`

2021-10-12 01:15 UTC, happythenewsad commented on services/QuillLMS/engines/evidence/lib/evidence/evidence/opinion_feedback_assembler.rb
> +      @top_feedback = feedbacks.empty? ? nil : feedbacks.min_by { |e| e.order }
I initially wrote it in one line, similar to your suggestion, but rubocop raised this error:
`Lint/SafeNavigationChain: Do not chain ordinary method call after safe navigation operator.`

2021-10-12 01:34 UTC, happythenewsad commented on services/QuillLMS/engines/evidence/lib/evidence/evidence/opinion_feedback_assembler.rb
> +      'Using Must' => '5545d756-9ba5-44d5-829a-0479cbbe941e',
Yes, we certainly could do something like this, but it requires an intermediate step of updating our entire ecosystem with these changes: gapi, oapi, golang, postman, LMS (Rule), and [rules.csv.](https://www.notion.so/quill/860620e6d04f448784182a878be45b50?v=6e07319b3db14e42b850a27bac37ca73) 

Do you want me to do this work before merging this PR, or after?

2021-10-12 01:37 UTC, happythenewsad commented on services/QuillLMS/engines/evidence/spec/controllers/evidence/opinion_controller_spec.rb
> +      context 'Rule.feedback exists' do
While I initially planned to use NewRelic.notice_error for these cases, I ended up letting them fail 'hard'. What's the desired behavior, if not failing hard (5xx)? I don't see a lot of value in returning HTTP 2xx and using NewRelic.notice_error, since the go server could interpret that as a green light to use the Oapi response.

2021-10-12 12:30 UTC, brendanshean commented on services/QuillLMS/engines/evidence/lib/evidence/evidence/opinion_feedback_assembler.rb
> +      @top_feedback = feedbacks.empty? ? nil : feedbacks.min_by { |e| e.order }
I think rubocop wants an extra `&` before the`min_by`:

`@top_feedback = @rule&.feedbacks&.min_by(&:order)`.

2021-10-12 13:45 UTC, dandrabik commented on services/QuillLMS/engines/evidence/spec/controllers/evidence/opinion_controller_spec.rb
> +      context 'Rule.feedback exists' do
I agree that's a possible path, but I don't think that's what the code will do. That is why a test would be helpful for these two scenarios. 

1. For the 500 error, I believe that `HTTParty` swallows 500 errors (e.g. you need to check if response was a `.success?` or use its `.code` method).
2. For the missing uid, you are essentially swallowing this error with `nil` checks. That works but I don't think the response is what we want, i.e. `optimal: nil`.

2021-10-12 13:49 UTC, dandrabik commented on services/QuillLMS/engines/evidence/lib/evidence/evidence/opinion_feedback_assembler.rb
> +      'Using Must' => '5545d756-9ba5-44d5-829a-0479cbbe941e',
I think since this is a new, unused API endpoint, I think it makes sense to migrate it before putting this endpoint in use (rather than putting it in use and having to migrate a live endpoint). I don't believe it involves all of those items, but either way, let's migrate it now.

2021-10-12 15:05 UTC, happythenewsad commented on services/QuillLMS/engines/evidence/lib/evidence/evidence/opinion_feedback_assembler.rb
> +      'Using Must' => '5545d756-9ba5-44d5-829a-0479cbbe941e',
@dandrabik OK, I'll create a ticket to capture this new work today, and pausing this PR for now

CC @brendanshean for awareness

2021-10-20 16:18 UTC, happythenewsad commented on services/QuillLMS/engines/evidence/lib/evidence/evidence/opinion/feedback_assembler.rb
> +        rule_uid = OAPI_ERROR_TO_RULE_UID.fetch(error)
fetch raises an exception when a key is not found.

2021-10-20 22:40 UTC, dandrabik approved these changes
:+1: LGTM. Small comment about giving an error a name (this helps with error monitoring and debugging), but once that is in place, :+1:

2021-10-20 22:40 UTC, dandrabik commented on services/QuillLMS/engines/evidence/lib/evidence/evidence/opinion/client.rb
> +            raise "Encountered upstream error: #{response}"
Let's name this error type, e.g. `OpinionAPIError`

2021-10-20 22:40 UTC, dandrabik commented on services/QuillLMS/engines/evidence/lib/evidence/evidence/opinion/client.rb
> +      API_TIMEOUT = 500
I like this short timeout. Noting that the longest request in the last 7 days was 132 ms, so this looks reasonable.

<img width="617" alt="Screen Shot 2021-10-20 at 6 36 48 PM" src="https://user-images.githubusercontent.com/1304933/138182112-6d5a66bd-f10d-4d26-984a-31aa3fb28d0b.png">

2021-10-21 20:29 UTC, merged