grammar API endpoint
empirical-org/Empirical-Core pull request #8436
Opened 2021-10-22 17:47 UTC by happythenewsad

## WHAT
Sibling to https://github.com/empirical-org/Empirical-Core/pull/8365 
Creates LMS Grammar endpoint, which intermediates between golang and GAPI

## WHY
So that GAPI and LMS are maximally decoupled, and so that we don't need to push complex config changes to gapi.

## HOW

### Screenshots
(If applicable. Also, please censor any sensitive data)

### Notion Card Links
https://www.notion.so/quill/Make-Grammar-API-endpoint-generic-74f14400f587408c90c006cefce186da

PR Checklist | Your Answer
------------ | -------------
Have you added and/or updated tests? |  yes
Have you deployed to Staging? | not yet
Self-Review: Have you done an initial self-review of the code below on Github? | ues
Spec Review: Have you reviewed the spec and ensured this meets requirements and/or matches design mockups? | yes

2021-10-22 17:49 UTC, happythenewsad commented on services/QuillLMS/engines/evidence/lib/evidence/evidence/grammar/feedback_assembler.rb
> +        { } # specify in class descendents
This mapping will be added in a separate ticket: https://www.notion.so/quill/Grammar-API-add-rule-lookup-and-update-rules-csv-with-snake-cased-rules-21e0f209b0e34f6a80b7571f92bb6f93

2021-10-28 15:24 UTC, happythenewsad commented
@dandrabik @anathomical nudge.

2021-10-28 17:10 UTC, dandrabik requested changes
Overall looks good. :+1: Thanks for putting this together.

I'm requesting some small naming changes, the main one being that we should only use snake_case for the keys (only lowercase and underscores) to be consistent. There are few that have quotes and dashes, let's do a sweep and clean those up, then this should be good to go!

2021-10-28 17:10 UTC, dandrabik commented on services/QuillLMS/engines/evidence/lib/evidence/evidence/grammar/client.rb
> +      class GAPIError < StandardError; end
I think we should refer to this API always as the `GrammarAPI`. Our app integrates with `Google` in many ways, so `GAPI` is more ambiguous than it needs to be.

2021-10-28 17:10 UTC, dandrabik commented on services/QuillLMS/engines/evidence/lib/evidence/evidence/grammar/feedback_assembler.rb
> +      def self.error_to_rule_uid
I think this should still be a constant. If you're trying to conform the subclass structure, this method could just return that constant, e.g.
```ruby
def self.error_to_rule_uid
  RULE_MAPPINGS
end

2021-10-28 17:10 UTC, dandrabik commented on services/QuillLMS/engines/evidence/lib/evidence/evidence/opinion/feedback_assembler.rb
> -      OAPI_ERROR_TO_RULE_UID = {
Same comment as above, but it would be good to keep this constant.

2021-10-28 17:10 UTC, dandrabik commented on services/QuillLMS/engines/evidence/lib/evidence/evidence/grammar/feedback_assembler.rb
> +          "articles_-_a_optimal" => '4c2962f1-03c4-449c-b821-8213688a9aa1',
I think we should remove the `-` from these names, e.g. `articles_a_optimal` instead of `articles_-_a_optimal`

2021-10-28 17:10 UTC, dandrabik commented on services/QuillLMS/engines/evidence/lib/evidence/evidence/grammar/feedback_assembler.rb
> +          "its_versus_it's_-_it's_optimal" => '8d8fe106-e0a5-440a-8bd4-4e34d8d0a16e',
Let's remove the `'` from this and replace it wish a `_`, e.g. `its_versus_it_s_it_s_optimal` instead of `its_versus_it's_-_it's_optimal`.

I'm less concerned about the actual name (If you have a better name feel free to use it), but we should restrict the keys to lowercase letters and underscores.

2021-10-29 17:10 UTC, anathomical approved these changes
I really dig the `FeedbackAssembler` abstraction.  Would love to expand that to other types of feedback generation (regex, automl, etc.)

2021-11-02 20:00 UTC, dandrabik approved these changes
:+1: LGTM. As we discussed, once the `.` are removed from the keys, ship it. :ship:

2021-11-03 19:33 UTC, merged