FeedbackAssembler specs, enhancements
empirical-org/Empirical-Core pull request #8464
Opened 2021-11-04 01:42 UTC by happythenewsad

## WHAT

## WHY

## HOW

### Screenshots
(If applicable. Also, please censor any sensitive data)

### Notion Card Links
(Please provide links to any relevant Notion card(s) relevant to this PR.)

PR Checklist | Your Answer
------------ | -------------
Have you added and/or updated tests? |  (The answer should mostly be 'YES'. If you answer 'NO', please justify.)
Have you deployed to Staging? | (Possible answers: YES, Not yet - deploying now!, NO - non-app change, NO - tiny change)
Self-Review: Have you done an initial self-review of the code below on Github? |
Spec Review: Have you reviewed the spec and ensured this meets requirements and/or matches design mockups? | (N/A or Yes)

2021-11-04 21:29 UTC, anathomical requested changes
I like the implementation in general, and appreciate the tests a ton.  A couple of thoughts on consolidation that might make things simpler?  Some of these probably should have been recommended back when the original OAPI changes were merged.

2021-11-04 21:29 UTC, anathomical commented on services/comprehension/feedback-api-main/src/endpoint/endpoint.go
> +
Why not re-use the pattern we have for other Evidence-engine-based APIs.  Like `automl_api` just uses `lms_domain`.

2021-11-04 21:29 UTC, anathomical commented on services/QuillLMS/engines/evidence/app/controllers/evidence/grammar_controller.rb
>  end
What if we just put this (and the Opinion API Controller) into the `FeedbackController`.  There are already endpoints there for different feedback types.  Consolidation of these single-action controllers is probably easier to keep track of.

2021-11-04 21:29 UTC, anathomical commented on services/QuillLMS/engines/evidence/lib/evidence/evidence/feedback_assembler.rb
> +      'abstract_error'
Maybe just `raise NoMethodError` or something here in the abstract class?  That'll actually cause errors if someone fails to do a sub-class implementation which I think is the behavior we want?

2021-11-09 16:24 UTC, cissyxyu approved these changes

2021-11-09 17:40 UTC, happythenewsad commented
@anathomical @cissyxyu Thanks for reviewing. This PR is blocked on https://www.notion.so/quill/blocked-Set-up-staging-Spell-model-servers-562b17d99b0b4266930c0fb227765420

I will address your changes once the PR becomes unblocked.

2022-01-06 22:52 UTC, cissyxyu approved these changes

2022-01-10 16:52 UTC, anathomical approved these changes

2022-01-10 20:26 UTC, merged