lms/add-script-to-set-activitities-private
empirical-org/Empirical-Core pull request #8667
Opened 2022-01-11 19:25 UTC by anathomical

## WHAT
Add a rake task that can set activities as "private" based on names in a CSV
## WHY
Curriculum has a list of 120 activities that they want to mass set to "private"
## HOW
Just take a pipe of a CSV file and parse each row to find an Activity by name and set the flag to `private`

### Notion Card Links
https://www.notion.so/quill/Change-these-activities-from-production-to-private-1966233fd36d47b8bf113191a8c8a96f

PR Checklist | Your Answer
------------ | -------------
Have you added and/or updated tests? | No tests on rake tasks
Have you deployed to Staging? | Deploying now
Self-Review: Have you done an initial self-review of the code below on Github? | Yes
Spec Review: Have you reviewed the spec and ensured this meets requirements and/or matches design mockups? | N/A

2022-01-11 19:31 UTC, happythenewsad requested changes
lets use `save!` instead of `save` so we know that persistence took place. Otherwise, looks good

2022-01-11 19:35 UTC, anathomical commented
> lets use `save!` instead of `save` so we know that persistence took place. Otherwise, looks good

@happythenewsad Good call.  Will update.

2022-01-11 19:57 UTC, emilia-friedberg approved these changes

2022-01-11 22:01 UTC, cissyxyu approved these changes

2022-01-12 15:25 UTC, happythenewsad approved these changes

2022-01-14 18:28 UTC, merged