lms/cache-teacher-scores-reporting
empirical-org/Empirical-Core pull request #8756
Opened 2022-01-27 21:12 UTC by anathomical

## WHAT
Update basic Teacher `/scores` caching
## WHY
To reduce database load on commonly-viewed reports.  This particular report is especially prevalent as it's one of the "default" report pages that a lot teachers land on even if they're going somewhere else.
## HOW
Wrap the payload construction code with the new user `classroom`-level caching code

### Notion Card Links
https://www.notion.so/quill/Implement-Caching-on-3-endpoints-07b97e6538134ea090ba0f7fd5df3d8b

PR Checklist | Your Answer
------------ | -------------
Have you added and/or updated tests? |  Yes
Have you deployed to Staging? | Yes
Self-Review: Have you done an initial self-review of the code below on Github? | Yes
Spec Review: Have you reviewed the spec and ensured this meets requirements and/or matches design mockups? | N/A

2022-01-28 13:27 UTC, emilia-friedberg requested changes

2022-01-28 13:27 UTC, emilia-friedberg commented on services/QuillLMS/app/controllers/teachers/classroom_manager_controller.rb
> +    json = current_user.classroom_cache(classroom, key: 'classroom_manager.teacher_dashboard_metrics', groups: cache_groups) do
I don't think this key can be right - shouldn't that be for the metrics that the teacher sees on their dashboard?

2022-01-28 16:00 UTC, anathomical commented on services/QuillLMS/app/controllers/teachers/classroom_manager_controller.rb
> +    json = current_user.classroom_cache(classroom, key: 'classroom_manager.teacher_dashboard_metrics', groups: cache_groups) do
Good catch!  That was definitely a copy-paste error on my part.  I've fixed it now.

2022-01-31 21:08 UTC, happythenewsad approved these changes

2022-01-31 21:08 UTC, happythenewsad commented on services/QuillLMS/app/controllers/teachers/classroom_manager_controller.rb
> +      last_page = scores.length < 200
nit: this should be `is_last_page` because of type boolean.

2022-02-01 13:01 UTC, emilia-friedberg approved these changes

2022-02-01 21:08 UTC, merged