Make Quill Evidence section of Teacher Center private
empirical-org/Empirical-Core pull request #8883
Opened 2022-02-28 18:00 UTC by brendanshean

## WHAT
The Teacher Center Reading Comprehension section can be found via Google. This should be visible to beta and gamma testers on Quill.

## WHY
We don't want this to be public.

## HOW
Add a check for AppSettings before rendering this particular show_topic page.

### Screenshots
(If applicable. Also, please censor any sensitive data)

### Notion Card Links
https://www.notion.so/quill/Quill-Evidence-section-of-Teacher-Center-findable-via-Google-search-should-be-private-c4aa1797772140749e9c012be7a25876

PR Checklist | Your Answer
------------ | -------------
Have you added and/or updated tests? |  (The answer should mostly be 'YES'. If you answer 'NO', please justify.)
Have you deployed to Staging? | (Possible answers: YES, Not yet - deploying now!, NO - non-app change, NO - tiny change)
Self-Review: Have you done an initial self-review of the code below on Github? |
Spec Review: Have you reviewed the spec and ensured this meets requirements and/or matches design mockups? | (N/A or Yes)

2022-03-01 17:30 UTC, happythenewsad requested changes
Note on your PR text: we should refer to this 'flag' as the 'comprehension app setting', since 'beta flag' refers to a different thing.

2022-03-01 17:30 UTC, happythenewsad commented on services/QuillLMS/app/models/blog_post.rb
> +  PUBLIC_TEACHER_TOPICS = TEACHER_TOPICS - [USING_QUILL_FOR_READING_COMPREHENSION]
How about moving this to the spec file, so that we're not adding app code for the sake of testing?

2022-03-02 13:12 UTC, brendanshean commented
> Note on your PR text: we should refer to this 'flag' as the 'comprehension app setting', since 'beta flag' refers to a different thing. If you actually meant to apply this logic to what Curriculum refers to as 'beta and gamma users', then use `User.flags` instead of `AppSetting::COMPREHENSION`

Good point.  I've adjusted the PR text language.

2022-03-02 15:29 UTC, happythenewsad approved these changes

2022-03-02 15:36 UTC, merged