Upgrade bundler to v2
empirical-org/Empirical-Core pull request #8906
Opened 2022-03-07 17:41 UTC by brendanshean

## WHAT
Upgrade bundler from 1.17.3 to 2.2.33.

## WHY
There's an incompatibility with M1 ARM architecture and our current version of `libv8`.  A workaround involves using the rosetta2 emulator to build gems using the older intel architecture.  This defeats the purpose of using the ARM processor though.  By upgrading bundler we don't have to use rosetta2 anymore.  

Also, Heroku supports bundler v2 and future upgrades to ruby will be streamlined with using a newer version of bundler.

## HOW
After `gem install -v 2.2.33`, run `bundle update --bundler`.

### Screenshots
(If applicable. Also, please censor any sensitive data)

### Notion Card Links
(Please provide links to any relevant Notion card(s) relevant to this PR.)

PR Checklist | Your Answer
------------ | -------------
Have you added and/or updated tests? |  No.  Configuration change.
Have you deployed to Staging? | YES
Self-Review: Have you done an initial self-review of the code below on Github? | YES
Spec Review: Have you reviewed the spec and ensured this meets requirements and/or matches design mockups? | N/A

2022-03-07 18:00 UTC, happythenewsad approved these changes

2022-03-07 18:11 UTC, anathomical requested changes
I don't actually see any place where this is actually specified.  I presume that that's because `bundler` is sort of outside the framework.  That said, we should at least update `bin/dev/bootstrap.sh` which has a note about pinning an older version due to incompatibility.

2022-03-07 18:15 UTC, brendanshean commented
> I don't actually see any place where this is actually specified. I presume that that's because `bundler` is sort of outside the framework. That said, we should at least update `bin/dev/bootstrap.sh` which has a note about pinning an older version due to incompatibility.

My guess is that circleci picks up the bundler version in the [Gemfile.lock](https://github.com/empirical-org/Empirical-Core/blob/develop/services/QuillLMS/Gemfile.lock#L928) but I also couldn't find anything explicit as to why that current version of bundler is there without a `gem install` call.

Good point on the bin/dev/bootstrap.sh
I will update that.

2022-03-07 18:26 UTC, anathomical approved these changes

2022-03-08 14:18 UTC, dandrabik approved these changes
:+1: Thanks for testing this helpful upgrade!

2022-03-09 13:44 UTC, merged