Update user-facing subscription plan names
empirical-org/Empirical-Core pull request #8924
Opened 2022-03-10 20:30 UTC by cissyxyu

## WHAT
We came up with a new set of official user-facing subscription names to show users on the "My Subscription" page. This PR changes that page to only show these new user-facing names and no longer show the old `account_type` and `subscriptionType`.

## WHY
This will provide a more unified and coherent user experience. It's confusing for users to see a bunch of slightly different plan names on their My Subscription page.

## HOW
Add a file `constants.js` that contains the official user-facing plan names.
Change the front end components to reference only the names in this file when displaying the plan name to users.

### Screenshots
<img width="1092" alt="Screen Shot 2022-03-10 at 2 21 56 PM" src="https://user-images.githubusercontent.com/57366100/157749237-c17c9bc9-c36b-46ee-8386-f5c2c3c76d97.png">
<img width="525" alt="Screen Shot 2022-03-09 at 1 46 23 PM" src="https://user-images.githubusercontent.com/57366100/157749246-99faa4f4-5f12-4612-b714-fa30d2df31b0.png">
<img width="985" alt="Screen Shot 2022-03-08 at 2 20 00 PM" src="https://user-images.githubusercontent.com/57366100/157749263-35a97569-449f-4270-8665-cd06467d48b6.png">

### Notion Card Links
https://www.notion.so/quill/Display-consistent-plan-names-on-MySubscriptions-page-f8e1225db4d9415cb76aeaf1b2292638

PR Checklist | Your Answer
------------ | -------------
Have you added and/or updated tests? |  YES
Have you deployed to Staging? | YES
Self-Review: Have you done an initial self-review of the code below on Github? | Yes
Spec Review: Have you reviewed the spec and ensured this meets requirements and/or matches design mockups? | Yes

2022-03-14 12:51 UTC, emilia-friedberg requested changes
This approach looks good to me, but I think since we are already introducing constants it makes sense to take things as a step further and solidify those constants in one place so that if we change a name later we don't need to go hunting through all these files.

2022-03-14 12:51 UTC, emilia-friedberg commented on services/QuillLMS/client/app/bundles/Teacher/components/subscriptions/current_subscription.jsx
> +    if (['School Premium', 'District Premium'].includes(subscriptionType)) {
We should make these their own constants in that `constants.js` file and then import them here since they're used for logic.

2022-03-14 12:51 UTC, emilia-friedberg commented on services/QuillLMS/client/app/bundles/Teacher/components/subscriptions/current_subscription.jsx
> +    } else if (subscriptionType === 'Teacher Premium Trial') {
Same with this and the rest of the places we're changing the display based on a plan name (and not just displaying it directly).

2022-03-14 12:51 UTC, emilia-friedberg commented on services/QuillLMS/client/app/bundles/Teacher/components/subscriptions/__tests__/__snapshots__/current_subscription.test.jsx.snap
> +                        tooltipText="You have a School Paid subscription"
Don't we want this to say School Premium now? That makes me feel like something is going awry.

2022-03-14 16:40 UTC, cissyxyu commented on services/QuillLMS/client/app/bundles/Teacher/components/subscriptions/__tests__/__snapshots__/current_subscription.test.jsx.snap
> +                        tooltipText="You have a School Paid subscription"
We actually want the tooltip to still display the account type. I think the idea is for Quill staff to more easily investigate and debug people's subscriptions.

2022-03-15 15:56 UTC, emilia-friedberg approved these changes
Awesome work, Cissy, thanks for cleaning that up.

2022-03-15 17:59 UTC, brendanshean approved these changes
Nice work on cleaning this up Cissy!

2022-03-15 20:12 UTC, merged