Segment/ add first and last name properties to identify
empirical-org/Empirical-Core pull request #9467
Opened 2022-08-03 16:39 UTC by eadams17

## WHAT
add first and last name properties to Segment identify calls; this also extracts some user methods and removes part of a check for the `diagnosticLanguageSelected` event that was causing it to not fire

## WHY
this is part of various Segment updates needed to optimize Ortto use

## HOW
extract user specific methods into model, add new properties

### Screenshots
(If applicable. Also, please censor any sensitive data)

### Notion Card Links
(Please provide links to any relevant Notion card(s) relevant to this PR.)
https://www.notion.so/quill/Add-first-name-and-last-name-to-Segment-Identify-call-cb28b2b0a3ec4a75a451dc1ce1ce17fc

PR Checklist | Your Answer
------------ | -------------
Have you added and/or updated tests? |  yes
Have you deployed to Staging? | yes
Self-Review: Have you done an initial self-review of the code below on Github? | yes
Spec Review: Have you reviewed the spec and ensured this meets requirements and/or matches design mockups? | yes

2022-08-03 16:50 UTC, brendanshean approved these changes
Looks good and I like the refactoring.

If after some time there ended up being lots of these segment hashes that were coupled to user, you could extract out into a decorator class using SimpleDelegator (e.g. I use that pattern where I want to extract out some methods that apply only to Stripe Subscriptions [StripeIntegration::Subscription](https://github.com/empirical-org/Empirical-Core/blob/develop/services/QuillLMS/app/models/stripe_integration/subscription.rb)).

2022-08-03 16:50 UTC, brendanshean commented on services/QuillLMS/app/models/user.rb
> +     Intercom: (role == 'teacher')
very minor nit:  `Intercom: teacher?`

2022-08-04 14:08 UTC, anathomical requested changes
I'd like to see a minor change around integration rules default behavior, but this looks good to me otherwise.

2022-08-04 14:08 UTC, anathomical commented on services/QuillLMS/app/services/analytics/segment_analytics.rb
> +    options[:integrations] = user&.segment_integration_rules
I think this is actually different behavior.  In the removed code if `user` is nil, we set a hash for `options[:integrations]` with `{ all: true, Intercom: false }`, but in the new code, if there is no user, this sets `options[:integrations]` to `nil`.  Basically, you're changing the fallback logic for when there is no valid `user` here.  I don't know how often that comes up, but I'd be a bit worried about it being more common than we expect.  Probably solvable with just an `|| default_integration_rules` thing here, where you pre-defined the `default_integration_rules with `Intercom: false`.

2022-08-04 14:08 UTC, anathomical commented on services/QuillLMS/client/app/bundles/Diagnostic/components/eslDiagnostic/languagePage.jsx
> +    if(language !== ENGLISH) {
Good catch on the issue here.  We probably actually DO want to be setting `NODE_ENV` on our environments, so in the long run we should probably revisit this, but no point in doing a whole bunch of work around that now.

2022-08-04 21:03 UTC, anathomical approved these changes
Looks good to me.  Thanks for making the change.

2022-08-08 15:37 UTC, merged