lms/remove-departed-staff
empirical-org/Empirical-Core pull request #9601
Opened 2022-08-26 14:57 UTC by anathomical

## WHAT
Remove departed staff members
## WHY
We want our Team page to be up to date
## HOW
Just remove the departed 

### Notion Card Links
https://www.notion.so/quill/Remove-offboarded-team-members-3e5d8c121bbd4c109111b39d43d686d6

PR Checklist | Your Answer
------------ | -------------
Have you added and/or updated tests? |  No tests on team content
Have you deployed to Staging? | Yes
Self-Review: Have you done an initial self-review of the code below on Github? | Yes
Spec Review: Have you reviewed the spec and ensured this meets requirements and/or matches design mockups? | N/A
Back-to-school 2022: Have you checked the [webinar schedule](https://www.notion.so/quill/Back-to-school-webinar-banners-2022-a75a89cfad9f434899ef6be3eb184733) to avoid for downtime/risky deploys? | N/A

2022-08-29 12:58 UTC, emilia-friedberg reviewed
It looks like this PR includes code around resetting the teacher activity feed as well as removing departed staff members.

2022-08-29 15:32 UTC, happythenewsad requested changes
Agree with @emilia-friedberg  - perhaps you created this branch off of #9604 instead of develop?

2022-08-29 19:16 UTC, anathomical commented
> Agree with @emilia-friedberg - perhaps you created this branch off of #9604 instead of develop?

@happythenewsad Good catch.  I've rebased on pushed, so should be ready for approval.

2022-08-30 01:02 UTC, happythenewsad approved these changes

2022-08-30 14:52 UTC, merged